<?php
/**
 * @var $this IWD_Opc_Block_Onepage_Agreements
 */
if (!empty($this->getAgreements())) {
    ?>
    <div id="iwd_opc_agreements">
        <form class="iwd_opc_form" id="iwd_opc_agreements_form">
            <?php foreach ($this->getAgreements() as $agreement) { ?>
                <div class="iwd_opc_one_agreement_content_container"
                     data-agreement-id="<?php echo $agreement->getId(); ?>">
                    <div class="iwd_opc_universal_wrapper iwd_opc_one_agreement_content">
                        <?php if ($agreement->getIsHtml()) { ?>
                            <?php echo $this->escapeHtml($agreement->getContent()); ?>
                        <?php } else { ?>
                            <?php echo $this->escapeHtml(nl2br($agreement->getContent())); ?>
                        <?php } ?>
                    </div>
                </div>
                <div class="iwd_opc_universal_wrapper iwd_opc_one_agreement">
                    <label class="iwd_opc_checkbox_label"
                           title="<?php echo $this->escapeHtml($agreement->getCheckboxText()); ?>"
                           for="iwd_opc_agreement_<?php echo $agreement->getId(); ?>">
                        <input type="checkbox"
                               id="iwd_opc_agreement_<?php echo $agreement->getId(); ?>"
                               name="agreement[<?php echo $agreement->getId(); ?>]"
                               value="1"
                               data-agreement-id="<?php echo $agreement->getId(); ?>"
                               class="iwd_opc_checkbox change-container-classname iwd_opc_field required-entry"/>
                        <span class="iwd_opc_checkbox_label_value"
                              data-agreement-id="<?php echo $this->escapeHtml($agreement->getId()); ?>">
                            <?php echo $this->escapeHtml($agreement->getCheckboxText()); ?>
                        </span>
                    </label>
                </div>
            <?php } ?>
        </form>
        <script type="text/javascript">
            var iwdOpcAgreementsForm = new VarienForm('iwd_opc_agreements_form');
            iwdOpcAgreementsForm.validator.options = {
                onSubmit: false,
                stopOnFirst: false,
                immediate: false,
                focusOnError: false,
                useTitles: false,
                onFormValidate: function (result, form) {
                },
                onElementValidate: function (result, elm) {

                }
            };
        </script>
    </div>
<?php } ?>