<?php
/**
 * @var $this IWD_Opc_Block_Onepage_Subscribe
 */
?>
<div class="iwd_opc_universal_wrapper">
    <label class="iwd_opc_checkbox_label"
           for="iwd_opc_subscribe_checkbox"
           title="<?php echo $this->escapeHtml($this->__('Sign Up For Newsletter')); ?>">
        <input type="checkbox"
               name="iwd_opc_subscribe_checkbox"
               id="iwd_opc_subscribe_checkbox"
               value="1"
            <?php if ($this->helper('iwd_opc')->isSubscribeByDefault()) { ?>
                checked="checked"
            <?php } ?>
               class="iwd_opc_checkbox iwd_opc_field"/>
        <span class="iwd_opc_checkbox_label_value">
            <?php echo $this->escapeHtml($this->__('Sign Up For Newsletter')); ?>
        </span>
    </label>
</div>