<div class="content-header">
    <table cellspacing="0">
        <tbody>
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-adminhtml-types">Subscription Types</h3></td>
            <td class="form-buttons">
                <button id="id_0acb842ecb6ead702e240def6eef2f41" title="Add New" type="button"
                        class="disabled scalable add" style=""><span><span><span>Add New</span></span></span></button>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<div>

    <div id="iwd_free_opc_locked_table_container">
        <table cellspacing="0" class="actions">
            <tbody>
            <tr>
                <td class="pager">
                    Page
                    <img src="<?php echo $this->getSkinUrl('images/pager_arrow_left_off.gif') ?>"
                         alt="Go to Previous page" class="arrow">

                    <input type="text" name="page" value="1" class="input-text page"
                           onkeypress="iwd_recurringpayments_types_gridJsObject.inputPage(event, '1')">

                    <img src="<?php echo $this->getSkinUrl('images/pager_arrow_right_off.gif') ?>" alt="Go to Next page"
                         class="arrow">

                    of 2 pages <span class="separator">|</span>
                    View <select name="limit">
                        <option value="20" selected="selected">20</option>
                        <option value="30">30</option>
                        <option value="50">50</option>
                        <option value="100">100</option>
                        <option value="200">200</option>
                    </select>
                    per page<span class="separator">|</span>
                    Total 38 records found <span id="iwd_recurringpayments_types_grid-total-count"
                                                 class="no-display">1</span>
                </td>
                <td class="filter-actions a-right">
                    <button id="id_ec59124ab950a1fdd13ca077958249f5" title="Reset Filter" type="button"
                            class="scalable disabled " style=""><span><span><span>Reset Filter</span></span></span>
                    </button>
                    <button id="id_f3128e2578206875aee8303a6b305853" title="Search" type="button"
                            class="scalable task disabled " style=""><span><span><span>Search</span></span></span>
                    </button>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="grid">
            <div class="hor-scroll">
                <table cellspacing="0" class="data" id="iwd_free_opc_locked_table">
                    <colgroup>
                        <col>
                        <col>
                        <col>
                        <col>
                        <col>
                        <col>
                        <col>
                        <col>
                    </colgroup>
                    <thead>
                    <tr class="headings">
                        <th><span class="nobr"><a href="#" name="id" title="asc" class="sort-arrow-desc"><span
                                            class="sort-title">Id</span></a></span></th>
                        <th><span class="nobr"><a href="#" name="title" title="asc" class="not-sort"><span
                                            class="sort-title">Title</span></a></span></th>
                        <th><span class="nobr"><a href="#" name="status" title="asc" class="not-sort"><span
                                            class="sort-title">Status</span></a></span></th>
                        <th><span class="nobr"><a href="#" name="billing_period_unit" title="asc" class="not-sort"><span
                                            class="sort-title">Billing Frequency</span></a></span></th>
                        <th><span class="nobr"><a href="#" name="trial_period" title="asc" class="not-sort"><span
                                            class="sort-title">Trial Period</span></a></span></th>
                        <th><span class="nobr"><a href="#" name="initial_fee" title="asc" class="not-sort"><span
                                            class="sort-title">Initial Fee</span></a></span></th>
                        <th><span class="nobr"><a href="#" name="created_at" title="asc" class="not-sort"><span
                                            class="sort-title">Created At</span></a></span></th>
                        <th class=" last"><span class="nobr"><a href="#" name="updated_at" title="asc" class="not-sort">
                                    <span
                                            class="sort-title">Updated At</span></a></span></th>
                    </tr>
                    <tr class="filter">
                        <th>
                            <div class="field-100"><input type="text" name="id"
                                                          id="iwd_recurringpayments_types_grid_filter_id" value=""
                                                          class="input-text no-changes" autocomplete="off"></div>
                        </th>
                        <th>
                            <div class="field-100"><input type="text" name="title"
                                                          id="iwd_recurringpayments_types_grid_filter_title" value=""
                                                          class="input-text no-changes"></div>
                        </th>
                        <th><select name="status" id="iwd_recurringpayments_types_grid_filter_status"
                                    class="no-changes">
                                <option value=""></option>
                                <option value="1">Enabled</option>
                                <option value="0">Disabled</option>
                            </select></th>
                        <th><select name="billing_period_unit"
                                    id="iwd_recurringpayments_types_grid_filter_billing_period_unit" class="no-changes">
                                <option value=""></option>
                                <option value="1_day">Daily</option>
                                <option value="1_week">Weekly</option>
                                <option value="2_weeks">2 Weeks</option>
                                <option value="3_weeks">3 Weeks</option>
                                <option value="1_month">Monthly</option>
                                <option value="2_months">2 Months</option>
                                <option value="3_months">3 Months</option>
                                <option value="6_months">6 Months</option>
                                <option value="1_year">Yearly</option>
                                <option value="2_years">2 Years</option>
                                <option value="3_years">3 Years</option>
                            </select></th>
                        <th><select name="trial_period" id="iwd_recurringpayments_types_grid_filter_trial_period"
                                    class="no-changes">
                                <option value=""></option>
                                <option value="0">No</option>
                                <option value="1">Yes</option>
                            </select></th>
                        <th><select name="initial_fee" id="iwd_recurringpayments_types_grid_filter_initial_fee"
                                    class="no-changes">
                                <option value=""></option>
                                <option value="0">No</option>
                                <option value="1">Yes</option>
                            </select></th>
                        <th>
                            <div class="range">
                                <div class="range-line date"><span class="label">From:</span>
                                    <input type="text"
                                           name="created_at[from]"
                                           value=""
                                           class="input-text no-changes"><img
                                            src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" alt=""
                                            class="v-middle"
                                            title="Date selector"></div>
                                <div class="range-line date"><span class="label">To :</span>
                                    <input type="text"
                                           name="created_at[to]"
                                           value=""
                                           class="input-text no-changes"><img
                                            src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" alt=""
                                            class="v-middle"
                                            title="Date selector"></div>
                            </div>
                            <input type="hidden" name="created_at[locale]" value="en_US"></th>
                        <th class=" last">
                            <div class="range">
                                <div class="range-line date"><span class="label">From:</span>
                                    <input type="text"
                                           name="updated_at[from]"
                                           value=""
                                           class="input-text no-changes"><img
                                            src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" alt=""
                                            class="v-middle"
                                            title="Date selector"></div>
                                <div class="range-line date"><span class="label">To :</span>
                                    <input type="text"
                                           name="updated_at[to]"
                                           value=""
                                           class="input-text no-changes"><img
                                            src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" alt=""
                                            class="v-middle"
                                            title="Date selector"></div>
                            </div>
                            <input type="hidden" name="updated_at[locale]" value="en_US"></th>
                    </tr>
                    </thead>

                    <tbody>
                    <tr class="even pointer">

                        <td class=" ">
                            15
                        </td>


                        <td class=" ">
                            Checkout Suite Pro
                        </td>


                        <td class=" ">
                            Enabled
                        </td>


                        <td class=" ">
                            Monthly
                        </td>


                        <td class=" ">
                            No
                        </td>


                        <td class=" ">
                            No
                        </td>


                        <td class=" ">
                            Sep 12, 2016 12:37:15 PM
                        </td>


                        <td class=" last">
                            Sep 12, 2016 12:37:15 PM
                        </td>

                    </tr>

                    <tr class="pointer">

                        <td class=" ">
                            14
                        </td>


                        <td class=" ">
                            day3
                        </td>


                        <td class=" ">
                            Enabled
                        </td>


                        <td class=" ">
                            Daily
                        </td>


                        <td class=" ">
                            Yes (5 Cycles)
                        </td>


                        <td class=" ">
                            No
                        </td>


                        <td class=" ">
                            Aug 22, 2016 4:45:06 AM
                        </td>


                        <td class=" last">
                            Aug 23, 2016 6:32:25 AM
                        </td>

                    </tr>

                    <tr class="even pointer">

                        <td class=" ">
                            13
                        </td>


                        <td class=" ">
                            day2
                        </td>


                        <td class=" ">
                            Enabled
                        </td>


                        <td class=" ">
                            Daily
                        </td>


                        <td class=" ">
                            No
                        </td>


                        <td class=" ">
                            No
                        </td>


                        <td class=" ">
                            Aug 19, 2016 2:29:46 AM
                        </td>


                        <td class=" last">
                            Aug 22, 2016 12:53:34 AM
                        </td>

                    </tr>

                    <tr class="pointer">

                        <td class=" ">
                            12
                        </td>


                        <td class=" ">
                            daynew
                        </td>


                        <td class=" ">
                            Enabled
                        </td>


                        <td class=" ">
                            Daily
                        </td>


                        <td class=" ">
                            Yes (6 Cycles)
                        </td>


                        <td class=" ">
                            No
                        </td>


                        <td class=" ">
                            Aug 19, 2016 2:17:15 AM
                        </td>


                        <td class=" last">
                            Aug 25, 2016 12:28:01 AM
                        </td>

                    </tr>

                    <tr class="even pointer">

                        <td class=" ">
                            11
                        </td>


                        <td class=" ">
                            3 Years
                        </td>


                        <td class=" ">
                            Enabled
                        </td>


                        <td class=" ">
                            3 Years
                        </td>


                        <td class=" ">
                            No
                        </td>


                        <td class=" ">
                            Yes
                        </td>


                        <td class=" ">
                            Aug 15, 2016 5:20:00 AM
                        </td>


                        <td class=" last">
                            Sep 14, 2016 5:35:10 AM
                        </td>

                    </tr>

                    <tr class="pointer">

                        <td class=" ">
                            10
                        </td>


                        <td class=" ">
                            2 Years
                        </td>


                        <td class=" ">
                            Enabled
                        </td>


                        <td class=" ">
                            2 Years
                        </td>


                        <td class=" ">
                            No
                        </td>


                        <td class=" ">
                            Yes
                        </td>


                        <td class=" ">
                            Aug 15, 2016 5:19:19 AM
                        </td>


                        <td class=" last">
                            Aug 19, 2016 5:51:10 AM
                        </td>

                    </tr>

                    <tr class="even pointer">

                        <td class=" ">
                            9
                        </td>


                        <td class=" ">
                            6 Months
                        </td>


                        <td class=" ">
                            Enabled
                        </td>


                        <td class=" ">
                            6 Months
                        </td>


                        <td class=" ">
                            Yes (1 Cycles)
                        </td>


                        <td class=" ">
                            Yes
                        </td>


                        <td class=" ">
                            Aug 15, 2016 5:18:10 AM
                        </td>


                        <td class=" last">
                            Aug 19, 2016 5:51:19 AM
                        </td>

                    </tr>

                    <tr class="pointer">

                        <td class=" ">
                            8
                        </td>


                        <td class=" ">
                            2 Months
                        </td>


                        <td class=" ">
                            Enabled
                        </td>


                        <td class=" ">
                            2 Months
                        </td>


                        <td class=" ">
                            Yes (1 Cycles)
                        </td>


                        <td class=" ">
                            Yes
                        </td>


                        <td class=" ">
                            Aug 15, 2016 5:17:47 AM
                        </td>


                        <td class=" last">
                            Aug 19, 2016 5:51:28 AM
                        </td>

                    </tr>

                    <tr class="even pointer">

                        <td class=" ">
                            7
                        </td>


                        <td class=" ">
                            3 Weeks
                        </td>


                        <td class=" ">
                            Enabled
                        </td>


                        <td class=" ">
                            3 Weeks
                        </td>


                        <td class=" ">
                            Yes (1 Cycles)
                        </td>


                        <td class=" ">
                            Yes
                        </td>


                        <td class=" ">
                            Aug 15, 2016 5:17:04 AM
                        </td>


                        <td class=" last">
                            Aug 19, 2016 5:51:36 AM
                        </td>

                    </tr>

                    <tr class="pointer">

                        <td class=" ">
                            6
                        </td>


                        <td class=" ">
                            2 Weeks
                        </td>


                        <td class=" ">
                            Enabled
                        </td>


                        <td class=" ">
                            2 Weeks
                        </td>


                        <td class=" ">
                            Yes (1 Cycles)
                        </td>


                        <td class=" ">
                            Yes
                        </td>


                        <td class=" ">
                            Aug 15, 2016 5:15:58 AM
                        </td>


                        <td class=" last">
                            Aug 15, 2016 5:20:44 AM
                        </td>

                    </tr>

                    <tr class="even">

                        <td class=" ">
                            4
                        </td>


                        <td class=" ">
                            Yearly
                        </td>


                        <td class=" ">
                            Enabled
                        </td>


                        <td class=" ">
                            Yearly
                        </td>


                        <td class=" ">
                            Yes (2 Cycles)
                        </td>


                        <td class=" ">
                            Yes
                        </td>


                        <td class=" ">
                            Aug 12, 2016 2:58:54 AM
                        </td>


                        <td class=" last">
                            Sep 6, 2016 5:12:30 AM
                        </td>

                    </tr>

                    <tr>

                        <td class=" ">
                            3
                        </td>


                        <td class=" ">
                            Weekly
                        </td>


                        <td class=" ">
                            Enabled
                        </td>


                        <td class=" ">
                            Weekly
                        </td>


                        <td class=" ">
                            Yes (1 Cycles)
                        </td>


                        <td class=" ">
                            Yes
                        </td>


                        <td class=" ">
                            Aug 12, 2016 2:35:33 AM
                        </td>


                        <td class=" last">
                            Aug 12, 2016 3:05:37 AM
                        </td>

                    </tr>

                    <tr class="even pointer">

                        <td class=" ">
                            2
                        </td>


                        <td class=" ">
                            Daily
                        </td>


                        <td class=" ">
                            Enabled
                        </td>


                        <td class=" ">
                            Daily
                        </td>


                        <td class=" ">
                            Yes (2 Cycles)
                        </td>


                        <td class=" ">
                            No
                        </td>


                        <td class=" ">
                            Aug 12, 2016 2:08:39 AM
                        </td>


                        <td class=" last">
                            Sep 1, 2016 3:51:05 AM
                        </td>

                    </tr>

                    <tr class="pointer">

                        <td class=" ">
                            1
                        </td>


                        <td class=" ">
                            Monthly
                        </td>


                        <td class=" ">
                            Enabled
                        </td>


                        <td class=" ">
                            Monthly
                        </td>


                        <td class=" ">
                            No
                        </td>


                        <td class=" ">
                            No
                        </td>


                        <td class=" ">
                            Aug 11, 2016 3:06:37 PM
                        </td>


                        <td class=" last">
                            Aug 19, 2016 5:52:00 AM
                        </td>

                    </tr>

                    </tbody>

                </table>
            </div>
        </div>
    </div>
</div>