<div class="content-header">
    <table cellspacing="0">
        <tbody>
        <tr>
            <td style="width:50%;"><h3 class="icon-head head-adminhtml-products">Subscription Products</h3></td>
            <td class="form-buttons">
                <button title="Add New" type="button" class="scalable disabled add" style="">
                    <span><span><span>Add New</span></span></span>
                </button>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<div>
    <div id="iwd_free_opc_locked_table_container">
        <table cellspacing="0" class="actions">
            <tbody>
            <tr>
                <td class="pager">
                    Page
                    <img src="<?php echo $this->getSkinUrl('images/pager_arrow_left_off.gif') ?>"
                         alt="Go to Previous page" class="arrow">

                    <input type="text" name="page" value="1" class="input-text page">

                    <img src="<?php echo $this->getSkinUrl('images/pager_arrow_right_off.gif') ?>" alt="Go to Next page"
                         class="arrow">

                    of 1 pages <span class="separator">|</span>
                    View <select name="limit">
                        <option value="20" selected="selected">20</option>
                        <option value="30">30</option>
                        <option value="50">50</option>
                        <option value="100">100</option>
                        <option value="200">200</option>
                    </select>
                    per page<span class="separator">|</span>
                    Total 9 records found
                    <span id="iwd_recurringpayments_products_grid-total-count" class="no-display">9</span>
                </td>
                <td class="filter-actions a-right">
                    <button id="id_d4b642dd6dbbedc4be342587cc185152" title="Reset Filter" type="button"
                            class="scalable disabled " style=""><span><span><span>Reset Filter</span></span></span>
                    </button>
                    <button id="id_669f8c352b63a31dbe69d5e6b3d6cde4" title="Search" type="button"
                            class="scalable task disabled " style=""><span><span><span>Search</span></span></span>
                    </button>
                </td>
            </tr>
            </tbody>
        </table>
        <div class="grid">
            <div class="hor-scroll">
                <table cellspacing="0" class="data" id="iwd_free_opc_locked_table">
                    <colgroup>
                        <col>
                        <col>
                        <col>
                        <col>
                        <col>
                        <col>
                        <col>
                    </colgroup>
                    <thead>
                    <tr class="headings">
                        <th><span class="nobr"><a href="#" name="id" title="asc" class="sort-arrow-desc"><span
                                            class="sort-title">Id</span></a></span></th>
                        <th><span class="nobr"><a href="#" name="product_name" title="asc" class="not-sort"><span
                                            class="sort-title">Product</span></a></span></th>
                        <th><span class="nobr"><a href="#" name="type_ids" title="asc" class="not-sort"><span
                                            class="sort-title">Subscription Types</span></a></span></th>
                        <th><span class="nobr"><a href="#" name="start_date_type" title="asc" class="not-sort"><span
                                            class="sort-title">Start Date</span></a></span></th>
                        <th><span class="nobr"><a href="#" name="is_subscription_only" title="asc"
                                                  class="not-sort"><span
                                            class="sort-title">Subscr. Only</span></a></span></th>
                        <th><span class="nobr"><a href="#" name="created_at" title="asc" class="not-sort"><span
                                            class="sort-title">Created At</span></a></span></th>
                        <th class=" last"><span class="nobr"><a href="#" name="updated_at" title="asc" class="not-sort">
                                    <span class="sort-title">Updated At</span></a></span></th>
                    </tr>
                    <tr class="filter">
                        <th>
                            <div class="field-100"><input type="text" name="id"
                                                          id="iwd_recurringpayments_products_grid_filter_id" value=""
                                                          class="input-text no-changes" autocomplete="off"></div>
                        </th>
                        <th>
                            <div class="field-100"><input type="text" name="product_name"
                                                          id="iwd_recurringpayments_products_grid_filter_product_name"
                                                          value="" class="input-text no-changes"></div>
                        </th>
                        <th><select name="type_ids" id="iwd_recurringpayments_products_grid_filter_type_ids"
                                    class="no-changes">
                                <option value=""></option>
                                <option value="1">Monthly</option>
                                <option value="2">Daily</option>
                                <option value="3">Weekly</option>
                                <option value="4">Yearly</option>
                                <option value="6">2 Weeks</option>
                                <option value="7">3 Weeks</option>
                                <option value="8">2 Months</option>
                                <option value="9">6 Months</option>
                                <option value="10">2 Years</option>
                                <option value="11">3 Years</option>
                                <option value="12">daynew</option>
                                <option value="13">day2</option>
                                <option value="14">day3</option>
                                <option value="15">Checkout Suite Pro</option>
                            </select></th>
                        <th><select name="start_date_type"
                                    id="iwd_recurringpayments_products_grid_filter_start_date_type" class="no-changes">
                                <option value=""></option>
                                <option value="by_customer">Selected by customer</option>
                                <option value="immediately">Moment of purchase</option>
                                <option value="last_day_of_month">Last day of month</option>
                                <option value="specific_day_of_month">Specific day of month</option>
                            </select></th>
                        <th><select name="is_subscription_only"
                                    id="iwd_recurringpayments_products_grid_filter_is_subscription_only"
                                    class="no-changes">
                                <option value=""></option>
                                <option value="0">No</option>
                                <option value="1">Yes</option>
                            </select></th>
                        <th>
                            <div class="range">
                                <div class="range-line date"><span class="label">From:</span>
                                    <input type="text"
                                           name="created_at[from]"
                                           value=""
                                           class="input-text no-changes"><img
                                            src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" alt=""
                                            class="v-middle"
                                            title="Date selector"></div>
                                <div class="range-line date"><span class="label">To :</span>
                                    <input type="text"
                                           name="created_at[to]"
                                           id="iwd_recurringpayments_products_grid_filter_created_at1476449250.4282_to"
                                           value=""
                                           class="input-text no-changes"><img
                                            src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" alt=""
                                            class="v-middle"
                                            title="Date selector"></div>
                            </div>
                            <input type="hidden" name="created_at[locale]" value="en_US"></th>
                        <th class=" last">
                            <div class="range">
                                <div class="range-line date"><span class="label">From:</span>
                                    <input type="text"
                                           name="updated_at[from]"
                                           value=""
                                           class="input-text no-changes"><img
                                            src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" alt=""
                                            class="v-middle"
                                            title="Date selector"></div>
                                <div class="range-line date"><span class="label">To :</span>
                                    <input type="text"
                                           name="updated_at[to]"
                                           id="iwd_recurringpayments_products_grid_filter_updated_at1476449250.4287_to"
                                           value=""
                                           class="input-text no-changes"><img
                                            src="<?php echo $this->getSkinUrl('images/grid-cal.gif') ?>" alt=""
                                            class="v-middle"
                                            title="Date selector"></div>
                            </div>
                            <input type="hidden" name="updated_at[locale]" value="en_US"></th>
                    </tr>
                    </thead>

                    <tbody>
                    <tr class="even pointer">

                        <td class=" ">
                            11
                        </td>


                        <td class=" ">
                            Simple pr. with all customer option1
                        </td>


                        <td class=" ">
                            <nobr>Monthly</nobr>
                            <br>
                            <nobr>Daily</nobr>
                            <br>
                            <nobr>Weekly</nobr>
                            <br>
                            <nobr>Yearly</nobr>
                            <br>
                            <nobr>2 Weeks</nobr>
                            <br>
                            <nobr>3 Weeks</nobr>
                            <br>
                            <nobr>2 Months</nobr>
                            <br>
                            <nobr>6 Months</nobr>
                            <br>
                            <nobr>2 Years</nobr>
                            <br>
                            <nobr>3 Years</nobr>
                        </td>


                        <td class=" ">
                            Moment of purchase
                        </td>


                        <td class=" ">
                            Yes
                        </td>


                        <td class=" ">
                            Aug 16, 2016 8:22:32 AM
                        </td>


                        <td class=" last">
                            Sep 14, 2016 5:45:48 AM
                        </td>

                    </tr>

                    <tr class="pointer">

                        <td class=" ">
                            10
                        </td>


                        <td class=" ">
                            ELEONOR'S APPLE ELEONOR'S APPLE ELEONOR'S APPLE $ 8 SNAK
                        </td>


                        <td class=" ">
                            <nobr>Weekly</nobr>
                            <br>
                            <nobr>day2</nobr>
                        </td>


                        <td class=" ">
                            Moment of purchase
                        </td>


                        <td class=" ">
                            Yes
                        </td>


                        <td class=" ">
                            Aug 16, 2016 12:33:30 AM
                        </td>


                        <td class=" last">
                            Aug 22, 2016 1:22:31 AM
                        </td>

                    </tr>

                    <tr class="even pointer">

                        <td class=" ">
                            8
                        </td>


                        <td class=" ">
                            Simple pr.
                        </td>


                        <td class=" ">
                            <nobr>Monthly</nobr>
                            <br>
                            <nobr>Daily</nobr>
                            <br>
                            <nobr>Weekly</nobr>
                            <br>
                            <nobr>Yearly</nobr>
                            <br>
                            <nobr>day2</nobr>
                            <br>
                            <nobr>day3</nobr>
                        </td>


                        <td class=" ">
                            Moment of purchase
                        </td>


                        <td class=" ">
                            No
                        </td>


                        <td class=" ">
                            Aug 15, 2016 12:32:23 AM
                        </td>


                        <td class=" last">
                            Sep 21, 2016 2:34:11 AM
                        </td>

                    </tr>

                    <tr class="pointer">

                        <td class=" ">
                            7
                        </td>


                        <td class=" ">
                            Gift card
                        </td>


                        <td class=" ">
                            <nobr>Monthly</nobr>
                            <br>
                            <nobr>Daily</nobr>
                            <br>
                            <nobr>Weekly</nobr>
                            <br>
                            <nobr>Yearly</nobr>
                        </td>


                        <td class=" ">
                            Last day of month
                        </td>


                        <td class=" ">
                            No
                        </td>


                        <td class=" ">
                            Aug 12, 2016 3:16:36 AM
                        </td>


                        <td class=" last">
                            Sep 2, 2016 3:52:16 AM
                        </td>

                    </tr>

                    <tr class="even">

                        <td class=" ">
                            6
                        </td>


                        <td class=" ">
                            Downloadable pr.
                        </td>


                        <td class=" ">
                            <nobr>Monthly</nobr>
                            <br>
                            <nobr>Daily</nobr>
                            <br>
                            <nobr>Weekly</nobr>
                            <br>
                            <nobr>Yearly</nobr>
                            <br>
                            <nobr>day2</nobr>
                        </td>


                        <td class=" ">
                            Moment of purchase
                        </td>


                        <td class=" ">
                            Yes
                        </td>


                        <td class=" ">
                            Aug 12, 2016 3:15:25 AM
                        </td>


                        <td class=" last">
                            Sep 7, 2016 12:46:57 AM
                        </td>

                    </tr>

                    <tr class="pointer">

                        <td class=" ">
                            5
                        </td>


                        <td class=" ">
                            Bundel pr.
                        </td>


                        <td class=" ">
                            <nobr>Monthly</nobr>
                            <br>
                            <nobr>Daily</nobr>
                            <br>
                            <nobr>Weekly</nobr>
                            <br>
                            <nobr>Yearly</nobr>
                            <br>
                            <nobr>day2</nobr>
                        </td>


                        <td class=" ">
                            Moment of purchase
                        </td>


                        <td class=" ">
                            Yes
                        </td>


                        <td class=" ">
                            Aug 12, 2016 3:11:59 AM
                        </td>


                        <td class=" last">
                            Sep 7, 2016 8:23:39 AM
                        </td>

                    </tr>

                    <tr class="even pointer">

                        <td class=" ">
                            4
                        </td>


                        <td class=" ">
                            Virtual pr.
                        </td>


                        <td class=" ">
                            <nobr>Monthly</nobr>
                            <br>
                            <nobr>Daily</nobr>
                            <br>
                            <nobr>Weekly</nobr>
                            <br>
                            <nobr>Yearly</nobr>
                            <br>
                            <nobr>daynew</nobr>
                            <br>
                            <nobr>day2</nobr>
                            <br>
                            <nobr>day3</nobr>
                        </td>


                        <td class=" ">
                            Moment of purchase
                        </td>


                        <td class=" ">
                            Yes
                        </td>


                        <td class=" ">
                            Aug 12, 2016 3:10:53 AM
                        </td>


                        <td class=" last">
                            Sep 6, 2016 7:43:35 AM
                        </td>

                    </tr>

                    <tr class="pointer">

                        <td class=" ">
                            3
                        </td>


                        <td class=" ">
                            Configurable pr.
                        </td>


                        <td class=" ">
                            <nobr>Monthly</nobr>
                            <br>
                            <nobr>Daily</nobr>
                            <br>
                            <nobr>Weekly</nobr>
                            <br>
                            <nobr>Yearly</nobr>
                            <br>
                            <nobr>day3</nobr>
                        </td>


                        <td class=" ">
                            Last day of month
                        </td>


                        <td class=" ">
                            No
                        </td>


                        <td class=" ">
                            Aug 12, 2016 3:09:00 AM
                        </td>


                        <td class=" last">
                            Sep 14, 2016 6:27:23 AM
                        </td>

                    </tr>

                    <tr class="even">

                        <td class=" ">
                            1
                        </td>


                        <td class=" ">
                            PSU publication downloadable 1
                        </td>


                        <td class=" ">
                            <nobr>Monthly</nobr>
                        </td>


                        <td class=" ">
                            Selected by customer
                        </td>


                        <td class=" ">
                            No
                        </td>


                        <td class=" ">
                            Aug 11, 2016 3:07:06 PM
                        </td>


                        <td class=" last">
                            Sep 20, 2016 3:23:49 AM
                        </td>

                    </tr>

                    </tbody>

                </table>
            </div>
        </div>
    </div>
</div>