<?php
/**
 * @var $this Mage_Payment_Block_Form_Checkmo
 */
?>
<?php if ($this->getMethod()->getMailingAddress() || $this->getMethod()->getPayableTo()) { ?>
    <?php if ($this->getMethod()->getPayableTo()) { ?>
        <div class="iwd_opc_universal_wrapper">
            <div class="iwd_opc_payment_label">
                <?php echo $this->escapeHtml($this->__('Make Payable To:')); ?>
            </div>
            <div class="iwd_opc_payment_text">
                <?php echo nl2br($this->getMethod()->getPayableTo()); ?>
            </div>
        </div>
    <?php } ?>
    <?php if ($this->getMethod()->getMailingAddress()) { ?>
        <div class="iwd_opc_universal_wrapper">
            <div class="iwd_opc_payment_label">
                <?php echo $this->escapeHtml($this->__('Send To:')); ?>
            </div>
            <div class="iwd_opc_payment_text">
                <?php echo nl2br($this->getMethod()->getMailingAddress()); ?>
            </div>
        </div>
    <?php } ?>
<?php } ?>
