<?php
/**
 * @var $this IWD_AuthorizeCIM_Block_Method_Echeck_Form
 */
?>

<?php
$code = $this->getMethodCode();
$haveStoredCards = $this->haveStoredCards();
$accountTypes = $this->getAccountTypeArray();
?>
<div id="payment_form_iwd_authorize_echeck">
    <?php if ($haveStoredCards): ?>
        <div class="iwd_opc_universal_wrapper">
            <div class="iwd_opc_payment_label">
                <?php echo $this->escapeHtml($this->__('Saved Bank Account')); ?>
            </div>
            <div class="iwd_opc_payment_text">
                <?php echo $this->escapeHtml(
                    $this->__('The following bank accounts are currently linked with your account.')
                ); ?>
            </div>
        </div>
        <div class="iwd_opc_universal_wrapper" id="iwd_authroize_net_echeck_saved_account">
            <?php
            $count = 0;
            foreach ($this->getStoredCards() as $card) {
                ?>
                <div class="iwd_opc_universal_wrapper">
                    <label class="iwd_opc_radio_label"
                           title="<?php echo $card->getLabel(); ?>"
                           for="<?php echo $card->getHash(); ?>">
                        <input type="radio"
                               class="iwd_opc_radio iwd_opc_field iwd_authorize_echeck_account"
                               name="payment[iwd_authorizecim_echeck_card_id]"
                               id="<?php echo $card->getHash(); ?>"
                               value="<?php echo $card->getHash(); ?>"
                               <?php if ($count == 0){ ?>checked="checked" <?php } ?>/>
                        <span class="iwd_opc_radio_label_value">
                    <?php echo $card->getLabel(); ?>
                </span>
                    </label>
                </div>
                <?php ++$count;
            } ?>
            <div class="iwd_opc_universal_wrapper">
                <label class="iwd_opc_radio_label"
                       title="<?php echo $this->__('Add new bank account'); ?>"
                       for="iwd_authorizecim_echeck_pay_type_new">
                    <input type="radio"
                           class="iwd_opc_radio iwd_opc_field iwd_authorize_echeck_account"
                           name="payment[iwd_authorizecim_echeck_card_id]"
                           id="iwd_authorizecim_echeck_pay_type_new"
                           value="0"/>
                    <span class="iwd_opc_radio_label_value">
                <?php echo $this->__('Add new bank account'); ?>
        </span>
                </label>
            </div>
        </div>
    <?php else: ?>
        <input name="payment[iwd_authorizecim_echeck_card_id]" id="iwd_authorizecim_echeck_card_id" type="hidden"
               value="0">
    <?php endif; ?>
    <div <?php if ($haveStoredCards){ ?>style="display:none"<?php } ?> id="iwd_authroize_net_echeck_new_account">
        <div class="iwd_opc_universal_wrapper">
            <input type="text"
                   title="<?php echo $this->escapeHtml($this->__('Name on Account')); ?>"
                   placeholder="<?php echo $this->escapeHtml($this->__('Name on Account')); ?>"
                   class="required-entry iwd_opc_field iwd_opc_input"
                   id="<?php echo $this->escapeHtml($code); ?>_account_name"
                   name="payment[iwd_echeck_account_name]"
                   maxlength="22"
                   value="<?php echo $this->escapeHtml($this->getInfoData('echeck_account_name')); ?>"
            />
        </div>
        <div class="iwd_opc_universal_wrapper">
            <input type="text"
                   title="<?php echo $this->escapeHtml($this->__('Bank Name')); ?>"
                   placeholder="<?php echo $this->escapeHtml($this->__('Bank Name')); ?>"
                   class="required-entry iwd_opc_field iwd_opc_input"
                   id="<?php echo $this->escapeHtml($code); ?>_bank_name"
                   name="payment[iwd_echeck_bank_name]"
                   maxlength="50"
                   value="<?php echo $this->escapeHtml($this->getInfoData('echeck_bank_name')); ?>"
            />
        </div>
        <div class="iwd_opc_universal_wrapper">
            <input type="text"
                   title="<?php echo $this->escapeHtml($this->__('Routing Number')); ?>"
                   placeholder="<?php echo $this->escapeHtml($this->__('Routing Number')); ?>"
                   class="required-entry iwd_opc_field iwd_opc_input"
                   id="<?php echo $this->escapeHtml($code); ?>_routing_no"
                   name="payment[iwd_echeck_routing_no]"
                   maxlength="9"
                   value="<?php echo $this->escapeHtml($this->getInfoData('echeck_routing_no')); ?>"
            />
        </div>
        <div class="iwd_opc_universal_wrapper">
            <input type="text"
                   title="<?php echo $this->escapeHtml($this->__('Account Number')); ?>"
                   placeholder="<?php echo $this->escapeHtml($this->__('Account Number')); ?>"
                   class="required-entry iwd_opc_field iwd_opc_input"
                   id="<?php echo $this->escapeHtml($code); ?>_account_no"
                   name="payment[iwd_echeck_account_no]"
                   maxlength="17"
                   value="<?php echo $this->escapeHtml($this->getInfoData('echeck_account_no')); ?>"
            />
        </div>
        <div class="iwd_opc_universal_wrapper">
            <select id="<?php echo $this->escapeHtml($code); ?>_account_type"
                    title="<?php echo $this->__('Account Type') ?>"
                    name="payment[iwd_echeck_account_type]"
                    class="iwd_opc_select iwd_opc_field required-entry">
                <?php foreach ($accountTypes as $k => $v) { ?>
                    <option value="<?php echo $k; ?>"
                            <?php if ($k == $this->getInfoData('echeck_account_type')): ?>selected="selected"<?php endif ?>>
                        <?php echo $v; ?>
                    </option>
                <?php } ?>
            </select>
        </div>
        <?php if (!$this->isGuest()) { ?>
            <?php if (!$this->getMethod()->getConfigData('allow_unsaved')) { ?>
                <div class="iwd_opc_universal_wrapper">
                    <label title="<?php echo $this->escapeHtml(
                        $this->__('Save Account')
                    ); ?>"
                           class="iwd_opc_checkbox_label"
                           for="<?php echo $this->escapeHtml($code); ?>_save">
                        <input type="checkbox"
                               id="<?php echo $this->escapeHtml($code); ?>_save"
                               value="1"
                               checked="checked"
                               name="payment[save]"
                               class="iwd_opc_checkbox iwd_opc_field"/>
                        <span class="iwd_opc_checkbox_label_value">
            <?php echo $this->escapeHtml(
                $this->__('Save Account')
            ); ?>
        </span>
                    </label>
                </div>
            <?php } else { ?>
                <div class="iwd_opc_universal_wrapper">
                    <input type="hidden"
                           name="payment[save]"
                           id="<?php echo $this->escapeHtml($code); ?>_new"
                           value="1"/>
                    <?php echo $this->escapeHtml(
                        $this->__('This data will be stored securely by our payment processor.')
                    ); ?>
                </div>
            <?php } ?>
        <?php } else { ?>
            <input type="hidden"
                   id="<?php echo $this->escapeHtml($code); ?>_new"
                   name="payment[save]"
                   value="0"/>
        <?php } ?>
    </div>
</div>

<?php if ($haveStoredCards): ?>
    <script type="text/javascript">
        //<![CDATA[
        window.hasOwnProperty=function(obj){return(this[obj])?true:false;};
        if(!window.hasOwnProperty('IWD')){IWD={};}
        IWD.AuthorizeCIMeCheck = IWD.AuthorizeCIMeCheck || {};
        IWD.AuthorizeCIMeCheck.Form = {
//            validateUrl: "<?php //echo Mage::helper('adminhtml')->getUrl('customer/authorizecim/validateBankAccount'); ?>//",
//            customerId: "<?php //echo $this->getCustomerId(); ?>//",
            init: function () {
                var _this = this;
                _this.sectionContainer = Singleton.get(PaymentMethod).sectionContainer;

                $ji(document).on('change', _this.sectionContainer + ' .iwd_authorize_echeck_account', function () {
                    if ($ji(this).val() == 0) {
                        IWD.AuthorizeCIMeCheck.Form.enableValidation();
                    } else {
                        IWD.AuthorizeCIMeCheck.Form.disableValidation();
                    }
                });

//                $ji(document).on('input', _this.sectionContainer + ' #iwd_authroize_net_echeck_new_account .iwd_opc_input', function () {
//                    _this.checkDuplicate();
//                });
            },

            disableValidation: function () {
                var _this = this;
                $ji(_this.sectionContainer + ' #iwd_authroize_net_echeck_new_account').hide();
                $ji(_this.sectionContainer + ' #iwd_authroize_net_echeck_new_account .iwd_opc_field')
                    .prop('disabled', true).hide();
            },

            enableValidation: function () {
                var _this = this;
                $ji(_this.sectionContainer + ' #iwd_authroize_net_echeck_new_account').show();
                $ji(_this.sectionContainer + ' #iwd_authroize_net_echeck_new_account .iwd_opc_field')
                    .prop('disabled', false).show().trigger('input');
            },

            getPaymentData: function () {
                var data = {};
                $ji('#payment_form_iwd_authorizecim input, #payment_form_iwd_authorizecim select').each(function () {
                    data[$ji(this).attr('name')] = $ji(this).val();
                });
                return data;
            },

            getPaymentObject: function () {
                var payment = {};
                payment['echeck_account_name'] = $ji('#iwd_authorizecim_echeck_account_name').val();
                payment['echeck_bank_name'] = $ji('#iwd_authorizecim_echeck_bank_name').val();
                payment['echeck_routing_no'] = $ji('#iwd_authorizecim_echeck_routing_no').val();
                payment['echeck_account_no'] = $ji('#iwd_authorizecim_echeck_account_no').val();
                payment['echeck_account_type'] = $ji('#iwd_authorizecim_echeck_account_type').val();
                return payment;
            },

//            checkDuplicate: function () {
//                var payment = IWD.AuthorizeCIMeCheck.Form.getPaymentObject();
//                var filed = true;
//                $ji.each(payment, function (key, val) {
//                    if (val == 0 || val == "") {
//                        filed = false;
//                    }
//
//                    return filed;
//                });
//
//                if (filed) {
//                    var formData = $ji.param(payment);
//                    $ji.ajax({
//                        url: IWD.AuthorizeCIMeCheck.Form.validateUrl,
//                        type: "POST",
//                        dataType: 'json',
//                        data: formData + "&customer_id=" + IWD.AuthorizeCIMeCheck.Form.customerId + IWD.AuthorizeCIMeCheck.Form.formKey(),
//                        success: function (result) {
//                            if (result.ajaxExpired) {
//                                Singleton.get(OnePage).ajaxError({status: 403});
//                            } else if (result.status && result.duplicate && result.message) {
//                                Singleton.get(PaymentMethod).showAjaxError(result.message);
//                            } else {
//                                Singleton.get(PaymentMethod).hideAjaxError();
//                            }
//                        },
//                        error: function () {
//                            Singleton.get(OnePage).ajaxError({status: 500});
//                        }
//                    });
//                }
//            },
//            formKey: function () {
//                if (typeof FORM_KEY != "undefined") {
//                    return "&form_key=" + FORM_KEY;
//                }
//
//                return '';
//            }
        };

        $ji(document).ready(function () {
            IWD.AuthorizeCIMeCheck.Form.init();
        });
        //]]>
    </script>
<?php endif; ?>

