<?php
/**
 * @var $this IWD_AuthorizeCIM_Block_Method_Cim_Form
 */
?>
<?php
$haveStoredCards = $this->haveStoredCards();
$acceptJsEnabled = $this->getMethod()->getConfigData('acceptjs_enable');
$isRequireCcv = $this->getMethod()->getConfigData('require_ccv');
$code = $this->getMethodCode();
?>
<div id="payment_form_iwd_authorizecim">
    <?php if ($haveStoredCards) { ?>
        <div class="iwd_opc_universal_wrapper">
            <div class="iwd_opc_payment_label">
                <?php echo $this->escapeHtml($this->__('Saved Cards')); ?>
            </div>
            <div class="iwd_opc_payment_text">
                <?php echo $this->escapeHtml(
                    $this->__('The following credit cards are currently linked with your account.')
                ); ?>
            </div>
        </div>
        <div class="iwd_opc_universal_wrapper" id="iwd_authroize_net_cim_saved_cards">
            <?php
            $count = 0;
            foreach ($this->getStoredCards() as $card) {
                $cardAdditional = $card->getAdditional();
                ?>
                <div class="iwd_opc_universal_wrapper">
                    <label class="iwd_opc_radio_label"
                           title="<?php echo $card->getLabel(); ?>"
                           for="<?php echo $card->getHash(); ?>">
                        <input type="radio"
                               class="iwd_opc_radio iwd_opc_field iwd_authorize_cim_card"
                               name="payment[iwd_authorizecim_card_id]"
                               id="<?php echo $card->getHash(); ?>"
                               value="<?php echo $card->getHash(); ?>"
                               <?php if ($count == 0){ ?>checked="checked" <?php } ?>
                        />
                        <span class="iwd_opc_radio_label_value">
                        <img src="<?php echo $this->getSkinUrl(
                            'css/iwd/opc/images/' . IWD_Opc_Helper_Data::getCardIcon($cardAdditional['cc_type'])
                        ) ?>"/>
                        xxxx - xxxx - xxxx - <?php echo $cardAdditional['cc_last4']; ?>
                            <br/>
                            <em><?php echo $this->__('Expires:'); ?></em>
                            <?php echo $cardAdditional['cc_exp_month']; ?>/<?php echo $cardAdditional['cc_exp_year']; ?>
                    </span>
                    </label>
                </div>
                <?php ++$count;
            } ?>
            <?php if ($isRequireCcv) { ?>
                <div class="iwd_opc_universal_wrapper">
                    <input type="text"
                           title="<?php echo $this->escapeHtml($this->__('CVV')); ?>"
                           placeholder="<?php echo $this->escapeHtml($this->__('CVV')); ?>"
                           class="iwd_opc_field iwd_opc_input required-entry validate-digits-range digits-range-001-9999"
                           id="<?php echo $this->escapeHtml($code); ?>_saved_cc_cid"
                           maxlength="4"
                           name="payment[saved_cc_cid]"
                           value=""/>
                    <span data-type="cvv" data-icon="&#xf059" class="iwd_opc_payment_tooltip"
                          data-content="<?php echo $this->escapeHtml(
                              $this->__('A 3 or 4-digit security code on the back or front of your card.')
                          ); ?>">
            </span>
                </div>
            <?php } ?>
            <div class="iwd_opc_universal_wrapper">
                <label class="iwd_opc_radio_label"
                       title="<?php echo $this->__('Enter a new credit card'); ?>"
                       for="iwd_authorizecim_pay_type_new">
                    <input type="radio"
                           class="iwd_opc_radio iwd_opc_field iwd_authorize_cim_card"
                           name="payment[iwd_authorizecim_card_id]"
                           id="iwd_authorizecim_pay_type_new"
                           value="0"/>
                    <span class="iwd_opc_radio_label_value">
                    <?php echo $this->__('Enter a new credit card'); ?>
            </span>
                </label>
            </div>
        </div>
    <?php } else { ?>
        <input name="payment[iwd_authorizecim_card_id]" type="hidden" value="0">
    <?php } ?>
    <div
        <?php if ($haveStoredCards){ ?>style="display:none"<?php } ?>
        id="iwd_authroize_net_cim_new_card">
        <div class="iwd_opc_universal_wrapper iwd_opc_cc_wrapper"
             data-https="<?php echo Mage::app()->getStore()->isCurrentlySecure() ? 1 : 0; ?>">
            <input type="text"
                   id="<?php echo $this->escapeHtml($code); ?>_iwd_opc_cc_number"
                <?php if ($acceptJsEnabled) { ?>
                    data-name="payment[iwd_opc_cc_number]"
                <?php } else { ?>
                    name="payment[iwd_opc_cc_number]"
                <?php } ?>
                   title="<?php echo $this->escapeHtml($this->__('Credit Card Number')); ?>"
                   placeholder="<?php echo $this->escapeHtml($this->__('Credit Card Number')); ?>"
                   maxlength="23"
                   class="required-entry iwd_opc_field iwd_opc_input validate-iwd-opc-cc-number validate-iwd-opc-cc-type"
                   value=""/>
            <input type="hidden"
                   id="<?php echo $this->escapeHtml($code); ?>_cc_number"
                   value=""
                <?php if ($acceptJsEnabled) { ?>
                    data-name="payment[cc_number]"
                <?php } else { ?>
                    name="payment[cc_number]"
                <?php } ?>
            />
            <?php if (Mage::app()->getStore()->isCurrentlySecure()) { ?>
                <span data-type="cc_on_https" data-icon="&#xf023" class="iwd_opc_payment_tooltip"
                      data-content="<?php echo $this->escapeHtml(
                          $this->__('Rest easy. Your credit card information is safely secured.')
                      ); ?>">
        </span>
            <?php } ?>
            <select id="<?php echo $this->escapeHtml($code); ?>_cc_type"
                <?php if ($acceptJsEnabled) { ?>
                    data-name="payment[cc_type]"
                <?php } else { ?>
                    name="payment[cc_type]"
                <?php } ?>
                    style="display: none;"
                    class="iwd_opc_select iwd_opc_field"
            >
                <option value=""></option>
                <?php foreach ($this->getCcAvailableTypes() as $typeCode => $typeName) { ?>
                    <option value="<?php echo $this->escapeHtml($typeCode); ?>">
                        <?php echo $this->escapeHtml($typeName); ?>
                    </option>
                <?php } ?>
            </select>
            <?php if ($this->getCcAvailableTypes()) { ?>
                <div class="iwd_opc_cc_types" style="display: none;">
                    <?php $i = 0;
                    foreach ($this->getCcAvailableTypes() as $typeCode => $typeName) {
                        if ($i == 3) {
                            break;
                        }
                        ?>
                        <div class="iwd_opc_cc_wrapper"
                             title="<?php echo $this->escapeHtml($typeName); ?>"
                             data-cc-type="<?php echo $this->escapeHtml($typeCode); ?>"></div>
                        <?php $i++;
                    } ?>
                    <?php if (count($this->getCcAvailableTypes()) > 3) { ?>
                        <div class="iwd_opc_cc_wrapper iwd_opc_more_cc_types">
                    <span data-type="cc_type" data-icon="&#xf055" class="iwd_opc_payment_tooltip">
                        <span class="iwd_opc_tooltip_content_fixed">
                            <?php foreach ($this->getCcAvailableTypes() as $typeCode => $typeName) { ?>
                                <div class="iwd_opc_cc_wrapper"
                                     title="<?php echo $this->escapeHtml($typeName); ?>"
                                     data-cc-type="<?php echo $this->escapeHtml($typeCode); ?>"></div>
                            <?php } ?>
                        </span>
                    </span>
                        </div>
                    <?php } ?>
                </div>
            <?php } ?>
        </div>
        <?php if ($this->getMethod()->getConfigData('useccv')){ ?>
        <div class="iwd_opc_short_fields">
            <?php } ?>
            <div class="iwd_opc_universal_wrapper">
                <?php
                $expCardValue = '';
                if ($this->getInfoData('cc_exp_month') && $this->getInfoData('cc_exp_year')) {
                    $expCardValue = $this->getInfoData('cc_exp_month') . '/' . $this->getInfoData('cc_exp_year');
                }
                ?>
                <input type="text"
                       id="<?php echo $this->escapeHtml($code); ?>_expiration_mon_yr"
                    <?php if ($acceptJsEnabled) { ?>
                        data-name="payment[iwd_opc_cc_exp]"
                    <?php } else { ?>
                        name="payment[iwd_opc_cc_exp]"
                    <?php } ?>
                       maxlength="7"
                       title="<?php echo $this->escapeHtml($this->__('MM/YYYY')); ?>"
                       placeholder="<?php echo $this->escapeHtml($this->__('MM/YYYY')); ?>"
                       class="iwd_opc_field iwd_opc_input required-entry validate-iwd-opc-cc-exp"
                       value="<?php echo $this->escapeHtml($expCardValue); ?>"/>
                <input type="hidden"
                       id="<?php echo $this->escapeHtml($code); ?>_expiration"
                       value="<?php echo $this->escapeHtml($this->getInfoData('cc_exp_month')); ?>"
                    <?php if ($acceptJsEnabled) { ?>
                        data-name="payment[cc_exp_month]"
                    <?php } else { ?>
                        name="payment[cc_exp_month]"
                    <?php } ?>
                />
                <input type="hidden"
                       id="<?php echo $this->escapeHtml($code); ?>_expiration_yr"
                       value="<?php echo $this->escapeHtml($this->getInfoData('cc_exp_year')); ?>"
                    <?php if ($acceptJsEnabled) { ?>
                        data-name="payment[cc_exp_year]"
                    <?php } else { ?>
                        name="payment[cc_exp_year]"
                    <?php } ?>
                />
            </div>
            <?php echo $this->getChildHtml(); ?>
            <?php if ($this->getMethod()->getConfigData('useccv')) { ?>
                <div class="iwd_opc_universal_wrapper">
                    <input type="text"
                           title="<?php echo $this->escapeHtml($this->__('CVV')); ?>"
                           placeholder="<?php echo $this->escapeHtml($this->__('CVV')); ?>"
                           class="iwd_opc_field iwd_opc_input required-entry validate-iwd-opc-cvv"
                           id="<?php echo $this->escapeHtml($code); ?>_cc_cid"
                           maxlength="4"
                        <?php if ($acceptJsEnabled) { ?>
                            data-name="payment[cc_cid]"
                        <?php } else { ?>
                            name="payment[cc_cid]"
                        <?php } ?>
                           value=""/>
                    <span data-type="cvv" data-icon="&#xf059" class="iwd_opc_payment_tooltip"
                          data-content="<?php echo $this->escapeHtml(
                              $this->__('A 3 or 4-digit security code on the back or front of your card.')
                          ); ?>">
            </span>
                </div>
            <?php } ?>
            <?php if ($this->getMethod()->getConfigData('useccv')){ ?>
        </div>
        <div class="iwd_opc_clear"></div>
    <?php } ?>
        <?php if (!$this->isGuest()) { ?>
            <?php if (!$this->isNominal() && !$this->getMethod()->getConfigData('allow_unsaved')) { ?>
                <div class="iwd_opc_universal_wrapper">
                    <label title="<?php echo $this->escapeHtml(
                        $this->__('Save Card')
                    ); ?>"
                           class="iwd_opc_checkbox_label"
                           for="<?php echo $this->escapeHtml($code); ?>_save">
                        <input type="checkbox"
                               id="<?php echo $this->escapeHtml($code); ?>_save"
                               value="1"
                               checked="checked"
                               name="payment[save]"
                               class="iwd_opc_checkbox iwd_opc_field"/>
                        <span class="iwd_opc_checkbox_label_value">
                <?php echo $this->escapeHtml(
                    $this->__('Save Card')
                ); ?>
            </span>
                    </label>
                </div>
            <?php } else { ?>
                <div class="iwd_opc_universal_wrapper">
                    <input type="hidden" name="payment[save]" value="1"/>
                    <?php echo $this->escapeHtml(
                        $this->__('This data will be stored securely by our payment processor.')
                    ); ?>
                </div>
            <?php } ?>
        <?php } else { ?>
            <input type="hidden" name="payment[save]" value="0"/>
        <?php } ?>
    </div>



    <?php if ($acceptJsEnabled) { ?>
        <input type="hidden" id="iwd_authcim_opaque_number" name="payment[opaque_number]" value=""/>
        <input type="hidden" id="iwd_authcim_opaque_descriptor" name="payment[opaque_descriptor]" value=""/>
        <input type="hidden" id="iwd_authcim_opaque_value" name="payment[opaque_value]" value=""/>
    <?php } ?>
</div>
<?php if ($haveStoredCards || $acceptJsEnabled) { ?>
    <script type="text/javascript">
        //<![CDATA[
        $ji(document).ready(function () {
            IWD.AuthorizeCIM.Form.validateUrl = "<?php echo $this->getUrl('customer/authorizecim/validateCard'); ?>";
            IWD.AuthorizeCIM.Form.customerId = "<?php echo $this->getCustomerId(); ?>";
            IWD.AuthorizeCIM.Form.clientKey = "<?php echo $this->getMethod()->getConfigData('acceptjs_key'); ?>";
            IWD.AuthorizeCIM.Form.apiLoginID = "<?php echo $this->getMethod()->getConfigData('login_id'); ?>";
            IWD.AuthorizeCIM.Form.acceptjsEnable = '<?php echo $acceptJsEnabled ? true : false ?>';
            IWD.AuthorizeCIM.Form.requireCcv = '<?php echo $isRequireCcv ? true : false ?>';
            IWD.AuthorizeCIM.Form.hasStoredCards = '<?php echo $haveStoredCards ? true : false ?>';

            IWD.AuthorizeCIM.Form.sectionContainer = Singleton.get(PaymentMethod).sectionContainer;
            IWD.AuthorizeCIM.Form.initStoredCards = function () {
                var self = this;
                if (!self.hasStoredCards) {
                    return;
                }

                $ji(document).on('change', self.sectionContainer + ' .iwd_authorize_cim_card', function () {
                    if ($ji(this).val() === '0') {
                        self.enableCardValidation();
                    } else {
                        self.changeCart();
                    }
                });

                if (self.acceptjsEnable) {
                    return;
                }

                $ji(document).on('change', '#iwd_authorizecim_expiration, #iwd_authorizecim_expiration_yr', function () {
                    self.checkDuplicate();
                });

                $ji(document).on('input', '#iwd_authorizecim_cc_number  , #iwd_authorizecim_cc_cid', function () {
                    self.checkDuplicate();
                });
            };

            IWD.AuthorizeCIM.Form.disableValidation = function () {
                var self = this;

                $ji(self.sectionContainer + ' #iwd_authroize_net_cim_new_card').hide();
                $ji(self.sectionContainer + ' #iwd_authorizecim_saved_cc_cid')
                    .prop('disabled', false).show().parent().show();
                $ji(self.sectionContainer + ' #iwd_authroize_net_cim_new_card .iwd_opc_field')
                    .prop('disabled', true).hide();
            };

            IWD.AuthorizeCIM.Form.initAcceptjs = function () {
                var self = this;
                if (!self.acceptjsEnable) {
                    return;
                }

                $ji(document).on('change', '#iwd_authorizecim_expiration, #iwd_authorizecim_expiration_yr', function () {
                    self.sendPaymentDataToAnet();
                });

                $ji(document).on('input', '#iwd_authorizecim_cc_number  , #iwd_authorizecim_cc_cid', function () {
                    self.sendPaymentDataToAnet();
                });

                window.iwdAuthCIMAcceptJsResponseHandler = function (response) {
                    IWD.AuthorizeCIM.Form.responseHandler(response);
                }
            };

            IWD.AuthorizeCIM.Form.enableCardValidation = function () {
                var self = this;

                $ji(self.sectionContainer + ' #iwd_authroize_net_cim_new_card').show();
                $ji(self.sectionContainer + ' #iwd_authorizecim_saved_cc_cid')
                    .prop('disabled', true).hide().parent().hide();
                $ji(self.sectionContainer + ' #iwd_authroize_net_cim_new_card .iwd_opc_field')
                    .prop('disabled', false).show();
            };

            IWD.AuthorizeCIM.Form.responseHandler = function (response) {
                Singleton.get(PaymentMethod).hideAjaxError();
                if (response.messages.resultCode === 'Error') {
                    var errors = '';
                    for (var i = 0; i < response.messages.message.length; i++) {
                        errors += response.messages.message[i].text + '<br/>';
                    }

                    Singleton.get(PaymentMethod).showAjaxError(errors);
                    $ji('#iwd_authcim_opaque_number').val('');
                    $ji('#iwd_authcim_opaque_descriptor').val('');
                    $ji('#iwd_authcim_opaque_value').val('');
                } else {
                    this.useOpaqueData(response.opaqueData);
                    this.checkDuplicate();
                }
            };

            IWD.AuthorizeCIM.Form.checkDuplicate = function (response) {
                var self = this;
                var payment = self.getPaymentObject();
                var filed = true;
                $ji.each(payment, function (key, val) {
                    if (val == 0 || val == "") {
                        filed = false;
                    }

                    return filed;
                });

                if (filed) {
                    var formData = $ji.param(payment);
                    $ji.ajax({
                        url: self.validateUrl,
                        type: "POST",
                        dataType: 'json',
                        data: formData + "&customer_id=" + self.customerId + IWD.AuthorizeCIM.formKey(),
                        success: function (result) {
                            if (result.ajaxExpired) {
                                Singleton.get(OnePage).ajaxError({status: 403});
                            } else if (result.status && result.duplicate && result.message) {
                                Singleton.get(PaymentMethod).showAjaxError(result.message);
                            } else {
                                Singleton.get(PaymentMethod).hideAjaxError();
                            }
                        },
                        error: function () {
                            Singleton.get(OnePage).ajaxError({status: 500});
                        }
                    });
                }
            };

            IWD.AuthorizeCIM.Form.changeCart = function () {
                IWD.AuthorizeCIM.Form.disableValidation();
            };

            IWD.AuthorizeCIM.Form.changePaymentData = function () {
                IWD.AuthorizeCIM.Form.disableValidation();
                IWD.AuthorizeCIM.Form.restoreCardId();
            };

            IWD.AuthorizeCIM.Form.init();
        });
        //]]>
    </script>
<?php } ?>
