<div class="giftcard">
    <h3><?php echo $this->__('Gift Cards') ?><span class='fa expand_plus'></span></h3>
    <div id="giftcard_balance_lookup"></div>
    <span id="gc-please-wait" class="please-wait" style="display:none;">
        <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" class="v-middle" /> <?php echo $this->__('Please wait, loading...') ?>
    </span>
    <form id="giftcard-form" action="<?php echo $this->getUrl('enterprise_giftcardaccount/cart/add') ?>" method="post">
        <fieldset>
            <label for="giftcard_code"><?php echo $this->__('Enter the gift card code') ?></label>
            <div class="v-fix"><input class="required-entry input-text" id="giftcard_code" name="giftcard_code" value="" /></div>
            <button class="button" onclick="IWD.OPC.GiftCard.submit()" type="button" value="<?php echo $this->__('Add Gift Card') ?>"><span><span><?php echo $this->__('Add Gift Card') ?></span></span></button>
            <button class="button check-gc-status" onclick="IWD.OPC.GiftCard.checkGiftCardStatus();" type="button" value="<?php echo $this->__('Check Gift Card status and balance') ?>"><span><span><?php echo $this->__('Check Gift Card status and balance') ?></span></span></button>
        </fieldset>
    </form>
</div>
